### ISSUE TITLE
HostFunc api

### ISSUE THREAD

**Issue by dtolnay** [yblein/rust-wasm#6]
I am having some trouble following how host funcs are supposed to be implemented. If I were implementing a host func to do something simple like:

```rust
fn f(x: i32, y: i32) -> i32 {
    y.wrapping_mul(2).wrapping_add(x)
}
```

could you show how to express this in the API expected by HostFunc?

```rust
fn f(stack: &mut Vec<Value>) -> Option<String> {
    /* ??? */
}
```

I see that the wasm signature needs to be `Func { args: [Int(I32), Int(I32)], result: [Int(I32)] })`. Naively I would expect that I need to pop two arguments from the stack and push the return value, but that doesn't seem to be right because this line asserts that my host func does not modify the size of the stack:

https://github.com/yblein/rust-wasm/blob/72fd2f9d2bd6cf9cacd0eb1c81e346c228ca9d37/src/interpreter.rs#L645

Thanks!

**Comment by yblein** [comment]
Hi @dtolnay 
Thanks for pointing this out, it is actually a very good question to which I don't have an answer right now. I took a quick look at the official interpreter to better understand what should be allowed there, but it turns out they do not have examples of host function call that modify their parameters or return a value.
The assertion you identified sure looks suspicious. We'll keep investing and keep you updated.

**Comment by dtolnay** [comment]
Thanks! FWIW I was able to comment out that assertion and all the following verification, and then my programs appear to run fine. I suppose this is really up to the implementation to define a calling convention for HostFuncs &mdash; in my case I require the HostFunc functions to pop all arguments and push all return values.

https://github.com/dtolnay/watt/blob/175481754e025c70664ed5e0a0965090ab852776/runtime/src/interpreter.rs#L838-L860

**Comment by yblein** [comment]
Oh you're the author of Watt; saw it r/rust a few days ago, cool stuff! I didn't noticed you were using our implementation :D
I see you've updated the sources to a more recent Rust version and fixed up a few things like unsafe code. Since you reformatted the code, patches would probably not apply well. I think I will directly back-port most of those changes if you don't mind.

You are right saying that we have some flexibility with the API for host functions, however I took another dab at the spec and it says "[a host function] must consume and produce the right number and types of WebAssembly values on the stack, according to its function type" (just as you expected). I think we'll fix the runtime checks you commented out in accordance, just to make sure that a single wrong call doesn't mess up everything, which is probably what we intended to do in the first place.
